---  
- hosts: webservers
  become: yes
  tasks:
    - name: ENABLED MOD_REWRITE
      apache2_module: name=rewrite state=present
      notify:
        - RESTART APACHE2
 
    - name: Copy website files to the server's document root
      copy:
        src: index.html
        dest: /var/www/html/index.html
        mode: preserve

  handlers:
    - name: RESTART APACHE2
      service: name=apache2 state=restart